### ISSUE TITLE
Support server password

### ISSUE THREAD

**Issue by kevinresol** [Hetsh/docker-stationeers#1]
...via the `-password` flag

**Comment by Hetsh** [comment]
Adding a password via flag would override the configuration in `default.ini`. This would potentially break the configuration for some people. I will try to come up with an alternative, that requires some testing though.
In the meantime, you might be able to add a password to `default.ini`. You can read about the configuration file `default.ini` on the [unofficial wiki](https://stationeers-wiki.com/Dedicated_Server_Guide#Configuration_from_default.ini).

**Comment by Hetsh** [comment]
Additional cli flags including `-password` can be added with the `SERVER_OPTS` environment variable like this:
```bash
--env SERVER_OPTS="-password='<your_pasword>'"
```
Commit is tagged with `0.2.2549.11996-2` and currently built by docker hub. It should not take long...
