### ISSUE TITLE
Increase update reliability

### ISSUE THREAD

**Issue by Hetsh** [Hetsh/docker-stationeers#4]
Find reliable alternative instead of scraping steamdb's website for new manifest IDs.

**Comment by spannerman79** [comment]
Steamdb uses https://github.com/SteamRE/SteamKit to pull their info.  _Maybe_ something like it can be done.

There is also a way via Python - https://github.com/ValvePython/steam

Something more slimlined - https://github.com/SteamRE/DepotDownloader - using `-manifest-only` might be more ideal.

All of SteamRE uses some form of dotNet

**Comment by Hetsh** [comment]
Thanks, i will look into it later this day.

**Comment by spannerman79** [comment]
I wanted to test for myself, so I went for the DepotDewnloader as it was much lighter to me.

I installed dotNet 2.2 (via AUR - you can get it any other way).

Grabbed https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.3.6/depotdownloader-2.3.6.zip
Extracted it.

`chmod u+x depotdownloader` after seeing what was in the file.

Ran the following;

```
./depotdownloader -app 600760 -manifest-only -dir ./rocket

No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 53
Got AppInfo for 600760
Using app branch: 'Public'.
Got depot key for 600762 result: OK
Downloading depot 600762 - Stationeers Dedicated Server(Linux)
Downloading depot manifest...Got CDN auth token for f3b7q2p3.ssl.hwcdn.net result: OK (expires 25/3/21 6:11:13 am)
 Done!
Manifest 7290294188270596278 (18/3/21 2:04:21 am)
Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots
Disconnected from Steam
```


`Manifest 7290294188270596278 (18/3/21 2:04:21 am)` is the only bit of info there.

Contents of ./rocket (named the directory just for the hell of it)

```
tree .
.
└── manifest_600762_7290294188270596278.txt

0 directories, 1 file
```

The first line within `manifest_600762_7290294188270596278.txt` is `18/3/21 2:04:21 am` the rest is just a list of file names and hashes.

Looks like the file output isn't needed if you do the following;

```
./depotdownloader -app 600760 -manifest-only -dir /tmp/rocket | grep Manifest
Manifest 7290294188270596278 (18/3/21 2:04:21 am)
```

I'm sure you can do something with that :smiley:

**Comment by Hetsh** [comment]
Thanks, all of these are great tools!

**Comment by Hetsh** [comment]
Well, i had hoped to find a simple API call to query the manifest id, but it is in fact a pretty complicated procedure.
I also found out that steamcmd provides similar functionality, although the JSON is not formatted correctly:

<details>
<summary>Manifest ID with SteamCMD</summary>

```
# steamcmd.sh +login anonymous +app_info_print 600760 +quit
...
AppID : 600760, change number : 10998447/0, last change : Thu Mar 18 15:30:28 2021 
"600760"
{
	"common"
	{
		"name"		"Stationeers Dedicated Server"
		"type"		"Tool"
		"parent"		"544550"
		"ReleaseState"		"released"
		"oslist"		"windows,linux"
		"osarch"		"64"
		"logo"		"cadc689734e4468b1e9e89327a7afad8cc05a841"
		"logo_small"		"cadc689734e4468b1e9e89327a7afad8cc05a841_thumb"
		"icon"		"1450e7f4ec567514855463d3691744795a99b425"
		"clienttga"		"bc91fde8f8886485a86c99ceb782c3644d66609e"
		"clienticon"		"80381c4b89907c6c635815bd42e7b605b1e45fd7"
		"associations"
		{
		}
		"gameid"		"600760"
	}
	"extended"
	{
		"gamedir"		""
	}
	"config"
	{
		"installdir"		"Stationeers Dedicated Server"
		"launch"
		{
			"0"
			{
				"executable"		"rocketstation_DedicatedServer.exe"
				"description"		"Dedicated Server with GUI settings"
				"type"		"server"
				"config"
				{
					"oslist"		"windows"
					"osarch"		"64"
				}
			}
			"1"
			{
				"executable"		"rocketstation_DedicatedServer.exe"
				"arguments"		"-batchmode"
				"description"		"Dedicated Server on background"
				"type"		"server"
				"config"
				{
					"oslist"		"windows"
					"osarch"		"64"
				}
			}
			"2"
			{
				"executable"		"rocketstation_DedicatedServer.x86_64"
				"arguments"		"-autostart -worldtype Space -batchmode -nographics"
				"type"		"server"
				"config"
				{
					"oslist"		"linux"
					"osarch"		"64"
				}
			}
		}
	}
	"depots"
	{
		"228988"
		{
			"name"		"VC 2019 Redist"
			"config"
			{
				"oslist"		"windows"
				"language"		""
			}
			"maxsize"		"29212147"
			"depotfromapp"		"228980"
			"sharedinstall"		"1"
		}
		"hasdepotsindlc"		"0"
		"600761"
		{
			"name"		"Stationeers Dedicated Server(Windows)"
			"config"
			{
				"oslist"		"windows"
				"osarch"		"64"
			}
			"manifests"
			{
				"public"		"1944451514540259678"
				"previous"		"4556055578249421776"
			}
			"maxsize"		"4046553450"
		}
		"600762"
		{
			"name"		"Stationeers Dedicated Server(Linux)"
			"config"
			{
				"oslist"		"linux"
				"osarch"		"64"
			}
			"manifests"
			{
				"public"		"7290294188270596278"
				"previous"		"353503925684212456"
			}
			"maxsize"		"4166499100"
		}
		"branches"
		{
			"public"
			{
				"buildid"		"6398512"
				"timeupdated"		"1616038694"
			}
			"beta"
			{
				"buildid"		"6398512"
				"description"		"beta branch"
				"timeupdated"		"1616033065"
			}
			"previous"
			{
				"buildid"		"6392313"
				"description"		""
				"timeupdated"		"1616038676"
			}
		}
	}
}
```
</details>

**Comment by Hetsh** [comment]
To keep things simple, i will increase the frequency of my update scripts, to hopefully reduce the delay,
If the delay is persists one of the tool will be implemented to issue a proper API request.

**Comment by spannerman79** [comment]
Just be aware of this - https://steamdb.info/faq/#can-i-use-auto-refreshing-plugins-or-automatically-scrape-crawl-steamdb:~:text=No%2C%20there's%20a%20chance%20you'll%20get,or%20other%20various%20Steam%20Web%20APIs

And as they use Cloudflare CDN;

```bash
dig NS +noadditional +noquestion +nocomments +nocmd +nostats steamdb.info
steamdb.info.           86400   IN      NS      rita.ns.cloudflare.com.
steamdb.info.           86400   IN      NS      todd.ns.cloudflare.com.
```
Trying to get your IP unbanned from Cloudflare is **not** simple.  And that was back when I did have a business plan on a domain that I use to have with them.

Not trying to pick or anything - just don't want others to go through the headache that I did ages ago.

**Comment by Hetsh** [comment]
Thanks i will keep this in mind. I promise to not DDOS them... :wink:

**Comment by mbround18** [comment]
For another project, we use the following command to get the latest update info: 
```
steamcmd +@ShutdownOnFailedCommand 1 +login anonymous +app_info_print GAME_ID +quit
```

and compare that to the app info at 
```
/path/to/steamapps/appmanifest_GAME_ID.acf
```

look for `buildid`

**Comment by Hetsh** [comment]
Thanks for the great tip @mbround18 it really works great. Not only does it print the buildID, but also the manifestID that we rely on.
This is a huge step in the right direction. The final goal would be to figure out the API request, so we can query this info without the steam client. I will try to do some research, but any hints will be greatly appreciated.

**Comment by mbround18** [comment]
@Hetsh sadly that is not a supported API request from Steam as documented on their steam web APIs 

https://developer.valvesoftware.com/wiki/Steam_Web_API

**Comment by Hetsh** [comment]
I did some work in 18bb3a8ade078cee901156491e8040cfd4c2f9de to parse the app_info output from SteamCMD with a shell script and it seems to work quite well. This solution really feels more like a workaround, but i did not find a way to just query an API with curl or something... Anyway, updates should be more consistent from now on.
