### ISSUE TITLE
Adapt to new dedicated server configuration

### ISSUE THREAD

**Issue by spannerman79** [Hetsh/docker-stationeers#7]
As per the recent [Atmospherics System Refactor](https://store.steampowered.com/news/app/544550/view/3327612290655617017) within that announcement there is [dedicated server guide](https://github.com/rocket2guns/StationeersDedicatedServerGuide/blob/main/README.md#settings) which outlines some new env vars.

I suggest adding those listed.

**Comment by Hetsh** [comment]
Hey again.
I basically had to throw out everything, since the server is configured completely different now. There is a new [branch](https://github.com/Hetsh/docker-stationeers/tree/server-rewrite) to adapt to the server rewrite. Feedback would be appreciated.

**Comment by spannerman79** [comment]
As you changed everything perhaps you should provide an example `docker-compose.yml`?

I should be able to work out how to update https://github.com/Hetsh/docker-stationeers/blob/main/docker-compose.yml to reflect what changes you have made.

**Comment by kevinresol** [comment]
Is this rewrite hosted on docker hub so that we can test?

**Comment by kevinresol** [comment]
I can't seem to find it so I built and pushed my own here: https://hub.docker.com/r/kevinresol/stationeers

And I can confirm it is working fine.

**Comment by Hetsh** [comment]
Thanks for testing @kevinresol. The game files are the same, but the configuration is different ([comparison](https://github.com/Hetsh/docker-stationeers/compare/server-rewrite)).

**Comment by kevinresol** [comment]
Would you deploy to docker hub please?

**Comment by kevinresol** [comment]
Thanks so much!
